#!/usr/bin/env python3
"""Generate the source-backed AI SDLC Loop skill catalog."""

from __future__ import annotations

import argparse
import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]
OUTPUT = ROOT / "docs/reference/skills.md"


def metadata(path: Path) -> tuple[str, str]:
    text = path.read_text(encoding="utf-8")
    match = re.match(r"---\n(.*?)\n---\n", text, re.DOTALL)
    if not match:
        raise ValueError(f"missing frontmatter: {path.relative_to(ROOT)}")
    values = {}
    for line in match.group(1).splitlines():
        key, separator, value = line.partition(":")
        if separator:
            values[key.strip()] = value.strip()
    return values.get("name", ""), values.get("description", "")


def render() -> str:
    rows = []
    for skill in sorted((ROOT / "skills").iterdir()):
        if not skill.is_dir():
            continue
        name, description = metadata(skill / "SKILL.md")
        if name != skill.name or not description:
            raise ValueError(f"invalid skill metadata: {skill.name}")
        kind = "Shared runtime" if name.endswith("shared-runtime") else "Working skill"
        rows.append(f"| `{name}` | {kind} | {description} |")
    return "\n".join((
        "<!-- Generated by docs/scripts/build_catalog.py. Do not edit by hand. -->",
        "# Skills",
        "",
        "This catalog is generated from distributed `SKILL.md` frontmatter.",
        "",
        "| Skill | Kind | Purpose |",
        "| --- | --- | --- |",
        *rows,
        "",
        f"Inventory: **{len(rows)} directories** — **{len(rows) - 1} working skills** and **1 shared runtime**.",
        "",
    ))


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    content = render()
    if args.check:
        if not OUTPUT.is_file() or OUTPUT.read_text(encoding="utf-8") != content:
            print(f"generated catalog is stale: {OUTPUT.relative_to(ROOT)}", file=sys.stderr)
            return 1
        print("skill catalog is current")
        return 0
    OUTPUT.write_text(content, encoding="utf-8")
    print(f"wrote {OUTPUT.relative_to(ROOT)}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
